version: 0.2
phases:
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
  build:
    commands:
      - echo "Entered build phase"
      - mvn clean verify -Dspring-boot.run.arguments='--spring.profiles.active=beta'
  post_build:
    commands:
      - echo "Entered the post-build phase"
      #- mv target/broetli-main-service-0.0.19.jar ./
artifacts:
  files:
    - target/broetli-main-service-0.0.19.jar
