version: '3.8'

services:
  main-service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres_db
    links:
      - postgres_db:database
  postgres_db:
    image: "postgres"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: broetli
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
